"""addCheckForBills

Revision ID: 66ae4f4cab4c
Revises: 927ed575acbd
Create Date: 2021-10-21 00:27:54.384555

"""

# revision identifiers, used by Alembic.
revision = '66ae4f4cab4c'
down_revision = '927ed575acbd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    if bind.engine.name == "sqlite":
        with op.batch_alter_table("bill", recreate="always") as batch_op:
            batch_op.add_column(
                sa.Column('check', sa.Boolean(), nullable=True),
            )
        with op.batch_alter_table("bill_version", recreate="always") as batch_op:
            batch_op.add_column(
                sa.Column('check', sa.Boolean(), nullable=True),
            )
    else:
        op.add_column('bill', sa.Column('check', sa.Boolean(), nullable=True))
        op.add_column('bill_version', sa.Column('check', sa.Boolean(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('billowers', 'person_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('billowers', 'bill_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
